plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ingwar.barabanchudes'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ingwar.barabanchudes'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.2-original-assets'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
